version: '3.8'

services:
  app:
    image: ghcr.io/gleb619/knca-signer:latest
    ports:
      - "8080:8080"
    volumes:
      # Mount certificate directories
      - ./certs:/app/certs:ro
      - ./backend/lib:/app/lib:ro
    environment:
      - LOGGING_LEVEL=INFO
#      - JAVA_OPTS=-Xmx512m -Djava.security.egd=file:/dev/urandom
#      - VERTX_CONFIG_PATH=/app/resources/application.yaml
#      - HTTP_PORT=8080
#      - HTTP_HOST=0.0.0.0
#      - CORS_ALLOWED_ORIGINS=*
#      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE
#      - CORS_ALLOWED_HEADERS=Content-Type,Authorization
#      - WEBSOCKET_PATH=/ws
#      - STATIC_CONFIG_WEB_ROOT=static
#      - CERTIFICATE_CERTS_PATH=certs/
#      - CERTIFICATE_CA_CERT_PATH=certs/ca.crt
#      - CERTIFICATE_KEY_SIZE=2048
#      - CERTIFICATE_KEY_FACTORY_TYPE=RSA
#      - CERTIFICATE_SIGNATURE_ALGORITHM=1.2.840.113549.1.1.11
#      - CERTIFICATE_KEYSTORE_PASSWORD=123456
#      - CERTIFICATE_CA_VALIDITY_YEARS=10
#      - CERTIFICATE_USER_VALIDITY_YEARS=1
#    restart: unless-stopped
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 40s
